[build]
    command = "yarn build"
    publish = "_site/"

[[redirects]]
    from = "https://benborgers.netlify.app/*"
    to = "https://benborgers.com/:splat"
    force = true

[[redirects]]
    from = "https://ben.city/*"
    to = "https://benborgers.com/:splat"
    force = true

[[redirects]]
    from = "/blog/*"
    to = "/posts/:splat"
