[[redirects]]
  from = "/slowmochristian/*"
  to = "https://slowmochristian.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/slowmochristian"
  to = "/slowmochristian/"
  status = 301
  force = true
