[build]
  command = "rm -rf dist && parcel build pages/* pages/**/* && node build.js"
  publish = "dist"

[dev]
  command = "parcel pages/* pages/**/*"

[[redirects]]
  from = "/blog/*"
  to = "/blog"
  status = 200