[[redirects]]
    from = "/blog/*"
    to = "/posts/:splat"

[[redirects]]
    from = "https://benborgers.netlify.app/*"
    to = "https://benborgers.com/:splat"
    force = true

[[redirects]]
    from = "/posts"
    to = "/"

[[redirects]]
    from = "/posts/16"
    to = "/posts/normalize-gatsby"

[[redirects]]
    from = "/posts/18"
    to = "/posts/kill-localhost"

[[redirects]]
    from = "/posts/19"
    to = "/posts/react-helmet-async"

[[redirects]]
    from = "/posts/20"
    to = "/posts/netlify-toml-gatsby"

[[redirects]]
    from = "/posts/23"
    to = "/posts/navigator-sendbeacon"

[[redirects]]
    from = "/posts/26"
    to = "/posts/google-sheets-json"

[[redirects]]
    from = "/posts/27"
    to = "/posts/gatsby-active-link"

[[redirects]]
    from = "/posts/30"
    to = "/posts/notion-blog"

[[redirects]]
    from = "/posts/32"
    to = "/posts/react-native-right-align"

[[redirects]]
    from = "/posts/33"
    to = "/posts/react-native-width"

[[redirects]]
    from = "/posts/37"
    to = "/posts/glitch-awake"

[[redirects]]
    from = "/posts/43"
    to = "/posts/swr-refresh"

[[redirects]]
    from = "/posts/44"
    to = "/posts/gatsby-google-fonts"

[[redirects]]
    from = "/posts/50"
    to = "/posts/notion-to-website"

[[redirects]]
    from = "/posts/52"
    to = "/posts/notion-table"

[[redirects]]
    from = "/posts/61"
    to = "/posts/netlify-functions-cors"

[[redirects]]
    from = "/posts/62"
    to = "/posts/vercel-cors"

[[redirects]]
    from = "/posts/65"
    to = "/posts/instagram-bio"

[[redirects]]
    from = "/posts/74"
    to = "/posts/vapor-migrations"

[[redirects]]
    from = "/posts/77"
    to = "/posts/express-password-protect"

[[redirects]]
    from = "/posts/86"
    to = "/posts/tailwind-postcss-error"

[[redirects]]
    from = "/posts/87"
    to = "/posts/vscode-spellcheck"

[[redirects]]
    from = "/posts/91"
    to = "/posts/tailwind-colors"

[[redirects]]
    from = "/posts/93"
    to = "/posts/node-serve-static-files"

[[redirects]]
    from = "/posts/101"
    to = "/posts/eleventy-tailwind"

[[redirects]]
    from = "/posts/104"
    to = "/posts/alpine-textarea-auto-resize"

[[redirects]]
    from = "/posts/106"
    to = "/posts/eleventy-katex"

[[redirects]]
    from = "/posts/108"
    to = "/posts/livewire-url-changing"

[[redirects]]
    from = "/posts/136"
    to = "/posts/laravel-plaintext-emails"
