backend:
  name: git-gateway
  branch: redesign
media_folder: static/assets
public_folder: assets
site_url: https://benborgers.com
collections:
  - label: Pages
    label_singular: page
    name: pages
    editor:
      preview: false
    files: 
      - label: Projects
        name: projects
        file: src/cms/projects.json
        fields:
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Text
                name: text
                widget: markdown
      - label: Client Work
        name: client_work
        file: src/cms/client_work.json
        fields:
          - label: projects
            name: projects
            widget: list
            fields: 
              - label: Text
                name: text
                widget: markdown