backend:
    name: git-gateway
    branch: main
media_folder: public/assets
public_folder: /assets
collections:
  - label: Pages
    label_singular: page
    name: pages
    editor: { preview: false }
    sortable_fields: []
    files:
      - label: Home
        name: home
        file: src/cms/home.json
        fields:
          - label: Bio
            name: bio
            widget: markdown
          - label: Bullets
            label_singular: bullet
            name: bullets
            widget: list
            fields:
              - label: Text
                name: text
                widget: markdown
                minimal: true
              - label: When
                name: when
                widget: string
  - label: Blog
    label_singular: blog post
    name: blog
    create: true
    slug: '{{fields.slug}}'
    editor: { preview: false }
    sortable_fields: ['date']
    folder: 'src/cms/blog'
    format: json
    fields:
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string
      - label: Description
        name: description
        widget: text
      - label: Date
        name: date
        widget: datetime
        time_format: false
        picker_utc: true
      - label: Published
        name: published
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown
