backend:
  name: git-gateway
media_folder: static/assets
public_folder: assets
site_url: https://benborgers.com
collections:
  - label: Pages
    label_singular: page
    name: pages
    editor:
      preview: false
    files: 
      - label: Projects
        name: projects
        file: src/cms/projects.json
        fields:
          - label: Projects
            name: projects
            widget: list
            fields:
              - label: Text
                name: text
                widget: markdown
      - label: Clients
        name: clients
        file: src/cms/clients.json
        fields:
          - label: projects
            name: projects
            widget: list
            fields: 
              - label: Text
                name: text
                widget: markdown
  - label: Invoices
    label_singular: Invoice
    name: invoices
    folder: src/cms/invoices
    identifier_field: id
    create: true
    editor: 
      preview: false
    format: json
    slug: "{{id}}"
    summary: "Invoice for {{client}}. Paid: {{paid}}."
    preview_path: "invoice/{{id}}"
    fields: 
      - label: ID
        name: id
        widget: string
        hint: random.org/strings/?num=1&len=6&digits=on&loweralpha=on&unique=on&format=plain&rnd=new
      - label: Created
        name: created
        widget: datetime
        timeFormat: false
      - label: Client
        name: client
        widget: string
      - label: Line Items
        label_singular: line item
        name: line_items
        widget: list
        fields: 
          - label: Description
            name: description
            widget: string
          - label: Amount
            name: amount
            widget: number
            min: 1
      - label: Paid
        name: paid
        widget: select
        options:
          - label: No
            value: "no"
          - label: Yes
            value: "yes"
        default: false
      - label: Description
        name: description
        widget: markdown
  - label: Reference
    label_singular: Reference
    name: reference
    folder: src/cms/reference
    create: true
    editor:
      preview: false
    format: json
    fields:
      - label: Title
        name: title
        widget: string
      - label: SEO Description
        name: seo_description
        widget: text
      - label: Last Updated
        name: last_updated
        widget: datetime
        timeFormat: false 
      - label: Published
        name: published
        widget: select
        options: 
          - label: No
            value: "no"
          - label: Yes
            value: "yes"
        default: false
      - label: Body
        name: body
        widget: markdown