backend:
  name: git-gateway

media_folder: static/assets
public_folder: assets

collections:
  - name: work
    label: Work Experience
    identifier_field: company
    folder: src/cms/work
    create: true
    fields:
      - { name: company, label: Company, widget: string }
      - { name: position, label: Position, widget: string }
      - { name: dates, label: Dates, widget: string }
      - { name: index, label: Index, widget: number, min: 1 }
    editor: 
      preview: false
  - name: client-work
    label: Client Work
    identifier_field: client
    folder: src/cms/client-work
    create: true
    fields: 
      - { name: client, label: Client, widget: string }
      - { name: description, label: Description, widget: markdown }
      - { name: link, label: Link, widget: string, required: false }
      - { name: index, label: Index, widget: number, min: 1 }
    editor: 
      preview: false
  - name: projects
    label: Personal Projects
    identifier_field: name
    folder: src/cms/projects
    create: true
    fields: 
      - { name: name, label: Name, widget: string }
      - { name: description, label: Description, widget: markdown }
      - { name: link, label: Link, widget: string, required: false }
      - { name: index, label: Index, widget: number, min: 1 }
    editor:
        preview: false