backend:
  name: git-gateway
  branch: main

site_url: https://benborgers.com

media_folder: _assets
static_folder: /assets

collections:
  - name: posts
    label: Posts
    label_singular: Post
    slug: '{{fields.slug}}'
    create: true
    preview_path: /posts/{{slug}}/
    editor: { preview: false }
    sortable_fields: []
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    folder: posts
    format: frontmatter
    fields:
      - label: Title
        name: title
        widget: string
      - label: Slug
        name: slug
        widget: string
      - label: Date
        name: date
        widget: datetime
        time_format: false
        picker_utc: true
        required: false
      - label: Tags
        name: tags
        widget: list
        required: false
      - label: Draft
        name: draft
        widget: boolean
        default: false
      - label: Body
        name: body
        widget: markdown
        modes: [raw]
        buttons: []
        editor_components: []
        required: false
