name: Puppeteer

on: push

jobs:
  puppeteer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      # `npm install` would install all the packages, but we don’t need
      # them all and that takes longer (it seems to be the longest step).
      - run: npm install
      - run: node scripts/puppeteer
        env:
          TONTINE_PASSWORD: ${{ secrets.TONTINE_PASSWORD }}
          JUMBOCASH_PASSWORD: ${{ secrets.JUMBOCASH_PASSWORD }}
