name: Puppeteer

on: push

jobs:
  puppeteer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: node scripts/puppeteer
        env:
          TONTINE_PASSWORD: ${{ secrets.TONTINE_PASSWORD }}
